config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
=begin
This is where the routes for my application are stored, devise allows authentication, 
resources are the posts/scores that are being created and the root is the homepage. 
=end 
  root to: "public#homepage"
end

app/models/admin.rb
class Admin < ApplicationRecord
=begin
This Class shows the authentication functions that are available through the devise gem, you can validate through postgresql, 
register new users, recover their password if lost and remember users. 
=end 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts

        end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
=begin
This Class adds validation to the form inwhich scores are input, it also makes sure the fixtures are listed by "latest first" scores.
=end    
    validates :home, presence: true
    validates :away, presence: true
    validates :homescr, presence: true, numericality: {only_integer: true}
    validates :awayscr, presence: true, numericality: {only_integer: true}

    belongs_to :admin

scope :order_by_latest_first, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
before_action :authenticate_admin!, except: [:show]
before_action :can_modify_post, only: [:edit, :update, :destroy]
  # GET /posts 
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.admin_id = current_admin.id

      if @post.save
        redirect_to post_url(@post), notice: "Post was successfully created." 
      else
        render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /posts/1
  def update
      if @post.update(post_params)
        redirect_to post_url(@post), notice: "Post was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
       redirect_to posts_url, notice: "Post was successfully destroyed." 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def can_modify_post
     redirect_back(fallback_location: root_path) and return unless @post.admin_id == current_admin.id
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:home, :away, :homescr, :awayscr)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def homepage
        @posts = Post.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<div class="container text-center" id="footer"> 
<p class="notice start-right"><%= notice %></p>
       <p class="alert start-right"><%= alert %></p>
</div>

app/views/layouts/_menu.html.erb
<h1 class="float-left" id="site-title">Fredy's Football Fun</h1><br>


<ul class="list-unstyled float-right" id="topnav">
<li> <%= link_to "Fixtures", root_path %></li>
<li> <%= link_to "Admin", posts_path %></li>
<% if admin_signed_in? %>
<li> <%= button_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
<% else %>
<li> <%= link_to "Sign In", new_admin_session_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : "Admin" %> | Fredy's Football Fun</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  </head>

  <body>
  
<div class='container'>

<div class='row'>

<div class='col page-nav'>
<%= render partial: "layouts/menu" %>
</div>
</div>
<div class='row'>

<div class='col'>

<%= yield %>

<%= render partial: "layouts/footer" %>
</div>

</div>
</div>


    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_fixtures.html.erb
<table class="table table-light text-center">
<thead class="thead-light">
<tr scope="row"><%= post.created_at.time.to_date %></tr>

  <tr>
    <th scope="col">Home Team</th>
    <th scope="col">Home Score</th>
    <th scope="col">Away Score</th>
    <th scope="col">Away Team</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><%= link_to post.home, post_path(post) %></td>
    <td><%=post.homescr %></td>
    <td><%=post.awayscr %></td>
    <td><%= link_to post.away, post_path(post) %></td>
</tr>
</tbody>
</table>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :home %>
    <%= form.text_field :home %>
  </div>

  <div class="field">
    <%= form.label :away %>
    <%= form.text_field :away %>
  </div>

  <div class="field">
    <%= form.label :homescr %>
    <%= form.number_field :homescr %>
  </div>

  <div class="field">
    <%= form.label :awayscr %>
    <%= form.number_field :awayscr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">


<table class="table table-light ">
<thead class="thead-light">
  <tr>
    <th scope="col"><strong>Home Team</strong></th>
    <th scope="col"><strong>Home Score</strong></th>
    <th scope="col"><strong>Away Score</strong></th>
    <th scope="col"><strong>Away Team</strong></th>
    
   
  </tr>
</thead>
<tbody>
  <tr>
  <td><%= post.home %></td>
  <td><%= post.homescr %></td>
    <td><%= post.awayscr %></td>
    <td><%= post.away %></td>
</tr>
</tbody>
</table>
 

</div>

app/views/posts/edit.html.erb
<div class="container container-fluid bg-light text-center w-50">
<h1>Edit result</h1>
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="bg-light" id="posts">
<h1 class="text-black bg-light pb-3 text-center">Enter your scores</h1>
  <% @posts.each do |post| %>
    <%= render post %>
    <p class="ml-3">
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
  </div>
<p class="bg-light w-25 text-center">
<%= link_to "New post", new_post_path %>
</p>

app/views/posts/new.html.erb
<div class="container container-fluid bg-light text-center w-50">
<h1>Submit Scores</h1>

<%= render "form", post: @post %>

<br>


  <%= link_to "Back to posts", posts_path %>
</div>
</div>
<div>

app/views/posts/show.html.erb
<div class="container bg-light p-3">

<%= render @post %>

<div class="text-black">
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>
  </div>
  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
</div>